source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rake', '~> 10.0.0'

gem 'cinch'
gem 'pry'
gem 'pry-nav'
gem 'sequel'
gem 'mysql2'
gem 'curb'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rvm'
gem 'filesize'
gem 'megahal'
gem 'rspec'
gem 'cinch-test'
gem 'webmock'
gem 'dalli'
gem 'nokogiri'
