source 'http://rubygems.org'

gem 'rake', '~> 10.0.0'

gem 'cinch'
gem 'pry'
gem 'pry-nav'
gem 'sequel'
gem 'mysql2', '= 0.5.2'
gem 'curb'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rvm'
gem 'filesize'
gem 'megahal', git: "https://github.com/pimeys/megahal"
gem 'rspec'
gem 'cinch-test'
gem 'webmock'
gem 'nokogiri'
gem 'ale_air'
gem 'influxdb'
